name: SportsWarehouse 

run-name: ${{ github.actor }} pushed

on: [push]

jobs:
  run-nba-database-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: P@55W0RD
          MYSQL_DATABASE: test_db #nba_stats
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Set up Python-3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Cache Pip Install
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys:
            ${{ runner.os }}-pip-

      - name: Pip Install
        run: |
          python3 -m pip install -r requirements.txt

      - name: NBA Database Test
        run: |
          pytest || echo