name: SportsWarehouse 
run-name: ${{ github.actor }} pushed ${{ github.run_attempt }}

on: [push]

jobs:
  run-nba-database-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: parafoxia/pip-install@v1
        name: Pip Install
        with:
          requirements: |
            requirements.txt 
      - name: ${{ github.run_number }}
        run: |
          echo "BOOOO-YAA"