name: SportsWarehouse 
run-name: ${{ github.actor }} pushed ${{ github.run_attempt }}

on: [push]

jobs:
  run-nba-database-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: Set up Python-3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          architecture: 'x64'
#      - uses: parafoxia/pip-install@v1
#        name: Pip Install
#        with:
#          requirements: |
#            requirements.txt 
      - name: Pip Install
        run: |
          python3 -m pip install -r requirements.txt
      - name: ${{ github.run_number }}
        run: |
          echo "BOOOO-YAA"
      - name: Where is Maria?
        run: |
          whereis mariadb
          whereis mysql
          whereis mysqld_safe